# Generated by Django 4.2 on 2024-02-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seller_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
