# Generated by Django 4.2 on 2024-02-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_seller_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_username',
            new_name='seller_id',
        ),
    ]
