# Generated by Django 4.2 on 2024-02-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_seller_username_product_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
    ]
